[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.41.0"
questdb-rs = "4.0.4"
tokio = { version = "1.45.0", features = [ "rt-multi-thread", "macros" ] }
simple_config = { git = "https://github.com/Eleocraft/simple_config_rs.git" }
futures = "0.3.31"
serde = { version = "1.0.218", features = ["derive"] }
ciborium = { version = "0.2.2" }
ciborium-io = { version = "0.2.2", features = ["std"] }
